### ISSUE TITLE
Server Error during initial instalation

### ISSUE THREAD

**Issue by r3pek** [IdeaSpaceVR/IdeaSpace#75]
Hi!
I'm trying to setup IdeaSpace but after setting up the DB connection details and User mail/pass/name I'm getting a server error and laravel.log contains the following:
Stack trace:
```
#0 /var/www/html/vendor/symfony/console/Input/ArrayInput.php(135): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/symfony/console/Input/Input.php(62): Symfony\Component\Console\Input\ArrayInput->parse()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(221): Symfony\Component\Console\Input\Input->bind()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run()
#5 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(170): Illuminate\Console\Application->call()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Foundation\Console\Kernel->call()
#10 /var/www/html/app/Http/Controllers/InstallationController.php(274): Illuminate\Support\Facades\Facade::__callStatic()
#11 [internal function]: App\Http\Controllers\InstallationController->install_user_config_submit()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call()
#15 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#17 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run()
#24 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#27 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#32 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#47 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#51 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch()
#57 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#60 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#62 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#64 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#68 /var/www/html/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#69 {main}  
```

Not really sure what's wrong here :(
EDIT: Database is created but the tables never get created

**Comment by weddingdj** [comment]
Which PHP version are you running on? 7.4?

**Comment by r3pek** [comment]
> Which PHP version are you running on? 7.4?

yes

**Comment by r3pek** [comment]
Can this be fixed with any other version (of PHP)?

**Comment by weddingdj** [comment]
I could be but I am not 100% sure. I will do a test shortly and my goal is to fix it so it works with PHP 7.4 as well.

**Comment by ohthehugemanatee** [comment]
I can replicate with a public "lamp stack" docker file. To replicate:
```
git clone https://github.com/sprintcube/docker-compose-lamp.git
cd docker-compose-lamp/
cp sample.env .env
rm -rf www
tar xzf IdeaSpace-1.2.2.tar.gz
mv IdeaSpace-1.2.2 www
chown -R 33:33 www
docker-compose up -d
```
- Access ideaspace at `http://localhost`, run through configuration (db host is "database", u/p are set in `.env`) , observe the error.
